"""Swath profiles: the BEFORE and AFTER ground points along a line picked on
the change map, drawn as a cross-section.

A swath is a strip SWATH_WIDTH wide centered on the profile line A -> A'.
Every point in it gets two coordinates:

    along  -- distance from A, measured along the line (the section's x axis)
    across -- signed distance from the centerline (+ = left of A -> A')

Plotting elevation against "along" squashes the swath's width onto the
centerline. On ground that also slopes across the swath, that smears each
epoch into a band tan(cross-slope) x SWATH_WIDTH thick -- 0.6 m for a 1 m
swath on a 30 degree slope. There are two options to correct this:

    tilt_swath_view    -- rotate the whole cloud by one angle about the
                          profile line and project it (rigid transformation).
    remove_cross_slope -- de-tilt every station by its own cross-slope, read
                          from the DEM. The swath collapses the whole way
                          along, but the shear coefficient changes with
                          station.

Either way both epochs get the same correction, so every vertical separation
between them at the same (along, across) survives untouched -- neither mode
can invent or hide change.

The AFTER tiles saved in the outputs are from before ICP alignment, so the
ICP transform generated by process_tile_pairs (icp_transforms.json) is
applied to them here -- the two epochs align as they were calculated by M3C2.
"""
import json
import tempfile
import tkinter as tk
import warnings

from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import numpy as np
import matplotlib.patheffects as patheffects

from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2Tk
from matplotlib.figure import Figure
from matplotlib.lines import Line2D
from matplotlib.offsetbox import AnchoredOffsetbox, DrawingArea
from matplotlib.patches import Circle, FancyArrow
from matplotlib.text import Text
from mpl_toolkits.axes_grid1.anchored_artists import AnchoredSizeBar
from osgeo import gdal
from scipy.ndimage import map_coordinates

from .pdal_runner import run_pipeline
from .las_metadata import read_las_header

# White outline drawn around the profile line/labels for readability
_HALO = [patheffects.withStroke(linewidth=4, foreground="white")]


def save_icp_transforms(path, transforms):
    """Save each tile pair's ICP transform, keyed by AFTER tile name"""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    record = {
        "description": (
            "ICP transform applied to each AFTER tile to align it to the "
            "BEFORE tile, in local coordinates (world + shift): "
            "aligned = matrix @ (xyz + shift) - shift"
        ),
        "tiles": transforms
    }

    with open(path, "w", encoding="utf-8") as f:
        json.dump(record, f, indent=2)

    return path


def load_icp_transforms(path):
    """Loads the per-tile ICP transforms saved by save_icp_transforms,
    or None (with a warning) if the file doesn't exist.
    """
    path = Path(path)

    if not path.exists():
        print(
            f"WARNING: no ICP transforms found ({path.name}) -- the AFTER points "
            f"will be shown WITHOUT the ICP alignment M3C2 used. Re-run the "
            f"change detection cell to save them."
        )
        return None

    with open(path, encoding="utf-8") as f:
        return json.load(f)["tiles"]


def apply_icp_transform(xyz, transform):
    """Apply ICP transform to global coordinates
    """
    shift = np.asarray(transform["shift"], dtype=float)
    matrix = np.asarray(transform["matrix"], dtype=float)

    local = xyz + shift
    aligned = local @ matrix[:3, :3].T + matrix[:3, 3]

    return aligned - shift


def _profile_axes(start, end):
    """Generate axes for profile based on start and end points.
    Returns starting point, unit vectors for along and across
    path directions, and profile length
    """
    start = np.asarray(start, dtype=float)
    end = np.asarray(end, dtype=float)

    length = float(np.hypot(*(end - start)))

    if length == 0:
        raise ValueError("The profile's start and end points are the same point")

    along = (end - start) / length
    across = np.array([-along[1], along[0]])

    return start, along, across, length


def to_swath_coordinates(x, y, start, end):
    """Convert map points to (along, across) coordinates"""
    origin, along_axis, across_axis, _ = _profile_axes(start, end)

    dx = np.asarray(x) - origin[0]
    dy = np.asarray(y) - origin[1]

    return dx * along_axis[0] + dy * along_axis[1], dx * across_axis[0] + dy * across_axis[1]


def swath_corners(start, end, width, margin=0.0):
    """Define the swath rectangle corners for cropping profile points
    """
    origin, along_axis, across_axis, length = _profile_axes(start, end)

    half = width / 2 + margin
    a = origin - margin * along_axis
    b = origin + (length + margin) * along_axis

    corners = [a + half * across_axis, b + half * across_axis, b - half * across_axis, a - half * across_axis]

    return np.array(corners + [corners[0]])


def _read_points_in_polygon(tile, polygon_wkt, work_dir, env=None):
    """Extract xyz coordinates of every point of one tile within
    the extent of polygon_wkt"""
    tile = Path(tile)
    csv_path = Path(work_dir) / f"{tile.stem}.csv"
    pipeline_path = Path(work_dir) / f"{tile.stem}.json"

    pipeline = [
        str(tile),
        {
            "type": "filters.crop",
            "polygon": polygon_wkt
        },
        {
            "type": "writers.text",
            "filename": str(csv_path),
            "format": "csv",
            "order": "X,Y,Z",
            "keep_unspecified": False,
            "precision": 3
        }
    ]

    run_pipeline(pipeline, pipeline_path, env=env)

    if not csv_path.exists():
        return np.empty((0, 3))

    # A tile with no points in the polygon writes just the header line
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", UserWarning)
        points = np.loadtxt(csv_path, delimiter=",", skiprows=1, ndmin=2)

    return points.reshape(-1, 3)


def read_swath_points(tiles, start, end, width, icp_transforms=None, margin=5.0, env=None, max_workers=8):
    """Extracts every point from tiles inside the swath and transforms
    them into (along, across, z) profile coordinate arrays.
    """
    # convert swath corners to wkt polygon for clipping
    corners = swath_corners(start, end, width, margin=margin)
    polygon_wkt = "POLYGON((" + ", ".join(f"{x:.3f} {y:.3f}" for x, y in corners) + "))"

    xmin, ymin = corners.min(axis=0)
    xmax, ymax = corners.max(axis=0)

    # Only read tiles whose extent overlaps the swath rectangle
    def overlaps(tile):
        header = read_las_header(tile, env=env)
        return header["minx"] <= xmax and header["maxx"] >= xmin and header["miny"] <= ymax and header["maxy"] >= ymin

    tiles = [tile for tile in tiles if overlaps(tile)]

    # Apply ICP transformation to extracted xyz points
    if icp_transforms is not None:
        missing = [Path(tile).stem for tile in tiles if Path(tile).stem not in icp_transforms]
        if missing:
            raise KeyError(f"No saved ICP transform for tile(s) {missing}")

    with tempfile.TemporaryDirectory() as work_dir:
        with ThreadPoolExecutor(max_workers=max_workers) as pool:
            chunks = list(pool.map(lambda tile: _read_points_in_polygon(tile, polygon_wkt, work_dir, env=env), tiles))

    if icp_transforms is not None:
        chunks = [apply_icp_transform(xyz, icp_transforms[Path(tile).stem]) for tile, xyz in zip(tiles, chunks)]

    xyz = np.vstack(chunks) if chunks else np.empty((0, 3))

    along, across = to_swath_coordinates(xyz[:, 0], xyz[:, 1], start, end)
    _, _, _, length = _profile_axes(start, end)

    inside = (along >= 0) & (along <= length) & (np.abs(across) <= width / 2)

    return along[inside], across[inside], xyz[inside, 2]


def cross_slope_along_profile(dem_path, start, end, smoothing=3.0):
    """Calculate cross-slope gradient at every DEM pixel along profile
    and average over smoothing window in meters.
    """
    gdal.UseExceptions()

    origin, along_axis, across_axis, length = _profile_axes(start, end)

    dataset = gdal.Open(str(dem_path))
    band = dataset.GetRasterBand(1)
    x0, pixel_width, _, y0, _, pixel_height = dataset.GetGeoTransform()
    pixel_height = abs(pixel_height)

    # Read only a window around the profile, not the whole DEM
    end_point = origin + length * along_axis
    pad = 3 * max(pixel_width, pixel_height)
    col0 = max(0, int(np.floor((min(origin[0], end_point[0]) - pad - x0) / pixel_width)))
    col1 = min(dataset.RasterXSize, int(np.ceil((max(origin[0], end_point[0]) + pad - x0) / pixel_width)))
    row0 = max(0, int(np.floor((y0 - max(origin[1], end_point[1]) - pad) / pixel_height)))
    row1 = min(dataset.RasterYSize, int(np.ceil((y0 - min(origin[1], end_point[1]) + pad) / pixel_height)))

    step = min(pixel_width, pixel_height) / 2
    stations = np.arange(0, length + step, step)
    stations[-1] = min(stations[-1], length)

    if col1 - col0 < 2 or row1 - row0 < 2:
        print("WARNING: the profile is outside the DEM -- no cross-slope correction applied")
        return stations, np.zeros_like(stations)

    dem = band.ReadAsArray(col0, row0, col1 - col0, row1 - row0).astype(float)
    nodata = band.GetNoDataValue()
    if nodata is not None:
        dem[dem == nodata] = np.nan
    dataset = None

    # np.gradient gives d/d(row) and d/d(column); rows run north -> south
    dz_drow, dz_dcol = np.gradient(dem, pixel_height, pixel_width)
    dz_dx, dz_dy = dz_dcol, -dz_drow

    # Bilinear sample at each station (pixel values sit at pixel centers)
    x = origin[0] + stations * along_axis[0]
    y = origin[1] + stations * along_axis[1]
    cols = (x - x0) / pixel_width - 0.5 - col0
    rows = (y0 - y) / pixel_height - 0.5 - row0

    sample = lambda grid: map_coordinates(grid, [rows, cols], order=1, mode="nearest")
    cross_slope = sample(dz_dx) * across_axis[0] + sample(dz_dy) * across_axis[1]

    # Moving average over smoothing window
    window = np.ones(min(len(stations), max(1, int(round(smoothing / step)))))
    valid = np.isfinite(cross_slope)
    total = np.convolve(np.where(valid, cross_slope, 0.0), window, mode="same")
    count = np.convolve(valid.astype(float), window, mode="same")

    with np.errstate(invalid="ignore", divide="ignore"):
        cross_slope = np.where(count > 0, total / count, 0.0)

    if not valid.all():
        print(
            f"WARNING: no DEM data for {100 * (1 - valid.mean()):.0f}% of the profile "
            f"-- no cross-slope correction there"
        )

    return stations, cross_slope


def remove_cross_slope(along, across, z, stations, cross_slope):
    """Calculate profile elevations with the cross-swath slope removed,
    so the swath collapses onto its centerline.

    Each point is moved across the local ground slope to the centerline:
        z_projected = z - cross_slope(along) * across
    A point on the ground surface plots at the elevation of the centerline,
    wherever it sits across the swath.

    Note that the shear coefficient changes from station to station,
    so this is not a rigid transform of the cloud.
    See tilt_swath_view for rigid transformation correction.
    """
    return z - np.interp(along, stations, cross_slope) * across


def describe_cross_slope(cross_slope, width):
    """One line summarizing the cross-slope correction, for printing."""
    tilt = np.degrees(np.arctan(np.abs(cross_slope)))

    return (
        f"Cross-swath slope: median {np.median(tilt):.0f} deg, max {tilt.max():.0f} deg "
        f"-- corrected a smear of up to {np.abs(cross_slope).max() * width:.2f} m "
        f"across the {width:g} m swath"
    )


def profile_tilt(cross_slope):
    """Calculates cross-slope tilt, in degrees, that best flattens the whole profile.

    Assumes the median of the per-station cross-slopes minimizes the swath's
    total leftover smear.
    """
    return float(np.degrees(np.arctan(np.median(cross_slope))))


def tilt_swath_view(across, z, tilt):
    """Applies tilt to calculate elevations along profile line.
    Equivalent to orthographic view in CloudCompare.

    Unlike remove_cross_slope, this rotates every point by the same angle,
    preserving geometry with rigid body rotations. Note the vertical axis
    measures distance perpendicular to the viewing direction rather than
    elevation. Thus visual change is foreshortened to dz * cos(tilt).
    """
    angle = np.radians(tilt)

    return z * np.cos(angle) - across * np.sin(angle)


def describe_tilt_view(cross_slope, tilt, width):
    """One line summarizing the tilted view, for printing."""
    residual = np.abs(cross_slope - np.tan(np.radians(tilt)))

    return (
        f"Tilted view: camera rotated {tilt:.0f} deg about the profile line "
        f"-- leaves a smear of median {np.median(residual) * width:.2f} m, "
        f"max {residual.max() * width:.2f} m across the {width:g} m swath, "
        f"wherever the ground does not match that one angle.\n"
        f"  Vertical change is foreshortened by cos({tilt:.0f} deg) = "
        f"{np.cos(np.radians(tilt)):.2f} in this view"
    )


def _draw_profile(ax, points, width, name, line_color="black"):
    """Draw A, A', centerline, and swath outline on axes ax
    """
    artists = []

    for point, label in zip(points, (name, f"{name}′")):
        artists += ax.plot(*point, marker="o", markersize=5, color=line_color, path_effects=_HALO)
        artists.append(
            ax.annotate(
                label, point, xytext=(6, 6), textcoords="offset points",
                fontsize=14, fontweight="bold", color=line_color, path_effects=_HALO
            )
        )

    if len(points) == 2:
        (x0, y0), (x1, y1) = points
        artists += ax.plot([x0, x1], [y0, y1], color=line_color, linewidth=1.5, path_effects=_HALO)

        outline = swath_corners(points[0], points[1], width)
        artists += ax.plot(outline[:, 0], outline[:, 1], color=line_color, linewidth=0.8)

    return artists


def pick_profile_endpoints(draw_map, width, name="A"):
    """Open the map in its own window and prompt user to click profile
    start (A) and end (A'). Returns ((x, y), (x, y)), rounded to 1 cm.

    draw_map(ax) draws the background map on a matplotlib Axes.
    """
    root = tk.Tk()
    root.title(f"Pick profile {name}-{name}'")

    result = {}

    try:
        instructions = tk.Label(
            root, justify="left", anchor="w", padx=8, pady=6,
            text=(
                f"Left-click the START ({name}) and then the END ({name}') of the profile.  "
                f"Right-click removes the last point.\n"
                f"To get closer first, use the zoom/pan tools below -- then click the "
                f"tool again to switch it off before picking points."
            )
        )
        instructions.pack(side=tk.TOP, fill=tk.X)

        size = 0.7 * min(root.winfo_screenwidth(), root.winfo_screenheight()) / 100
        fig = Figure(figsize=(size, size), dpi=100)
        ax = fig.add_subplot()
        draw_map(ax)

        canvas = FigureCanvasTkAgg(fig, master=root)
        fig.tight_layout()

        buttons = tk.Frame(root)
        buttons.pack(side=tk.BOTTOM, fill=tk.X, pady=4)

        toolbar = NavigationToolbar2Tk(canvas, root, pack_toolbar=False)
        toolbar.update()
        toolbar.pack(side=tk.BOTTOM, fill=tk.X)

        canvas.get_tk_widget().pack(side=tk.TOP, fill=tk.BOTH, expand=True)

        points = []
        artists = []

        def accept():
            result["points"] = list(points)
            root.quit()

        def cancel():
            root.quit()

        accept_button = tk.Button(buttons, text="Use this profile", state=tk.DISABLED, command=accept)
        accept_button.pack(side=tk.RIGHT, padx=8)
        tk.Button(buttons, text="Cancel", command=cancel).pack(side=tk.RIGHT)

        def redraw():
            for artist in artists:
                artist.remove()
            artists[:] = _draw_profile(ax, points, width, name)
            accept_button.config(state=tk.NORMAL if len(points) == 2 else tk.DISABLED)
            canvas.draw_idle()

        def on_click(event):
            # Clicks are for the zoom/pan tool while it's switched on
            if event.inaxes is not ax or canvas.widgetlock.locked() or event.dblclick:
                return

            if event.button == 1:
                if len(points) == 2:
                    points.clear()  # a third click starts a new profile
                points.append((event.xdata, event.ydata))
                redraw()

            elif event.button == 3 and points:
                points.pop()
                redraw()

        canvas.mpl_connect("button_press_event", on_click)
        root.protocol("WM_DELETE_WINDOW", cancel)

        # Bring the window in front of the browser once, without pinning it there
        root.attributes("-topmost", True)
        root.after(500, lambda: root.attributes("-topmost", False))
        root.focus_force()

        root.mainloop()

    finally:
        root.destroy()

    if "points" not in result:
        raise RuntimeError("Profile picking was cancelled")

    start, end = [(round(float(x), 2), round(float(y), 2)) for x, y in result["points"]]

    return start, end


def plot_profile_location(ax, start, end, width, name="A", padding=None):
    """Draw the point profile location on a zoomed in map
    """
    _, _, _, length = _profile_axes(start, end)

    _draw_profile(ax, [tuple(start), tuple(end)], width, name)

    if padding is None:
        padding = max(0.5 * length, 25)

    (x0, y0), (x1, y1) = start, end
    half = max(abs(x1 - x0), abs(y1 - y0)) / 2 + padding
    ax.set_xlim((x0 + x1) / 2 - half, (x0 + x1) / 2 + half)
    ax.set_ylim((y0 + y1) / 2 - half, (y0 + y1) / 2 + half)

    # Full coordinates on the axes (not "+3.819e6"-style offsets)
    ax.ticklabel_format(useOffset=False, style="plain")

    # Move the map's legend, if it has one, outside -- zoomed in, it would
    # cover much of the map
    legend = ax.get_legend()
    if legend is not None:
        ax.legend(
            legend.legend_handles, [text.get_text() for text in legend.get_texts()],
            title=legend.get_title().get_text(),
            loc="upper left", bbox_to_anchor=(1.02, 1), frameon=False
        )

    ax.set_title(f"Profile {name}–{name}′ ({width:g} m swath)")


def _nice_length(target):
    """Determine the largest 1, 2 or 5 x 10^n that's no bigger than target."""
    power = 10 ** np.floor(np.log10(target))
    return max(step * power for step in (1, 2, 5) if step * power <= target)


def world_axes_on_screen(along_axis, tilt):
    """Where E, N and Z point on the page, for a tilted section.
    """
    a_x, a_y = along_axis
    angle = np.radians(tilt)

    return {
        "E": (a_x, a_y * np.sin(angle)),
        "N": (a_y, -a_x * np.sin(angle)),
        "Z": (0.0, np.cos(angle)),
    }


def _axis_depth(along_axis, tilt):
    """How far each world axis points away from the viewer, same view as
    world_axes_on_screen. Positive is into the page; an axis with no length
    on the page is aimed straight at or straight away from the viewer.
    """
    a_x, a_y = along_axis
    angle = np.radians(tilt)

    return {"E": -a_y * np.cos(angle), "N": a_x * np.cos(angle), "Z": np.sin(angle)}


def _draw_axis_triad(ax, along_axis, tilt, radius=26, edge=0.25):
    """Draw a small N/E/Z triad below the section's lower left corner.

    Each arrow is a world axis as the view projects it, drawn against a unit
    circle: an arrow short of the circle is an axis this view foreshortens.
    """
    screen = world_axes_on_screen(along_axis, tilt)
    depth = _axis_depth(along_axis, tilt)
    gray = str(edge)

    # Labels sit outside the unit circle, so the box has to be wider than it
    margin = 11
    box = DrawingArea(2 * (radius + margin), 2 * (radius + margin), 0, 0)
    center = np.array([radius + margin, radius + margin])

    # Unit circle: anything inside it is being foreshortened by the view
    box.add_artist(Circle(center, radius - 1, fill=False, ec="0.75", lw=0.7, ls=(0, (3, 3))))

    label_at = {}

    for name, vector in screen.items():
        vector = np.array(vector) * (radius - 1)
        length = np.hypot(*vector)

        if length < 0.15 * radius:
            # Axis aimed at the viewer -- draw the end of it, not a stub
            box.add_artist(Circle(center, 3.2, fill=False, ec=gray, lw=1.2))
            if depth[name] > 0:
                for dx, dy in ((2.3, 2.3), (2.3, -2.3)):
                    box.add_artist(Line2D(
                        [center[0] - dx, center[0] + dx], [center[1] - dy, center[1] + dy],
                        color=gray, lw=1.0
                    ))
            else:
                box.add_artist(Circle(center, 1.1, color=gray))
            label_at[name] = center + np.array([0.42, -0.42]) * radius
        else:
            box.add_artist(FancyArrow(
                center[0], center[1], vector[0], vector[1],
                width=0.7, head_width=4.5, head_length=5.0,
                length_includes_head=True, color=gray
            ))
            label_at[name] = center + vector * (1 + 7.5 / length)

    # Two axes that project onto one line share a label position -- at tilt 0
    # the horizontal plane is edge-on, so E and N both lie along the section.
    # Push any colliding pair apart, across the arrows.
    names = list(label_at)
    for i, first in enumerate(names):
        for second in names[i + 1:]:
            if np.hypot(*(label_at[first] - label_at[second])) >= 11:
                continue
            across = np.array([-screen[first][1], screen[first][0]])
            span = np.hypot(*across)
            across = np.array([0.0, 1.0]) if span < 1e-9 else across / span
            label_at[first] = label_at[first] + across * 7.5
            label_at[second] = label_at[second] - across * 7.5

    for name, position in label_at.items():
        label = Text(
            position[0], position[1], name, color=gray,
            ha="center", va="center", fontsize=9, fontweight="bold"
        )
        label.set_path_effects(_HALO)
        box.add_artist(label)

    # pad keeps a fixed gap under the section
    ax.add_artist(AnchoredOffsetbox(
        loc="upper left", child=box, pad=0.5, borderpad=0,
        bbox_to_anchor=(0, -0.02), bbox_transform=ax.transAxes, frameon=False
    ))


def plot_swath_section(ax, epochs, length, name="A", width=None, tilt_note=None,
                       triad=None, marker_size=10):
    """Plot a point profile cross-section with no vertical exaggeration

    epochs is a list of (along, z, label, color), drawn in that order
    length is the profile's length (m)
    tilt_note names the cross-slope treatment in the title
    """
    for along, z, label, color in epochs:
        ax.scatter(along, z, s=marker_size, marker="s", color=color, linewidths=0, label=label)

    ax.set_aspect("equal")  # true scale -- no vertical exaggeration
    ax.set_xlim(-0.01 * length, 1.01 * length)
    ax.set_axis_off()

    # A and A' just above the section's two ends
    for x, label, align in ((0, name, "left"), (length, f"{name}′", "right")):
        ax.text(x, 1.02, label, transform=ax.get_xaxis_transform(), ha=align, va="bottom", fontsize=16)

    bar_length = _nice_length(length / 4)
    ax.add_artist(
        AnchoredSizeBar(
            ax.transData, bar_length, f"{bar_length:g} m",
            loc="upper right", bbox_to_anchor=(1, -0.02), bbox_transform=ax.transAxes,
            frameon=False, label_top=False, size_vertical=bar_length / 40, sep=4, borderpad=0,
            fontproperties={"size": 12}
        )
    )

    ax.legend(
        title="Lidar ground points", loc="upper left", bbox_to_anchor=(1.02, 1),
        frameon=False, markerscale=2, fontsize=11, title_fontsize=11
    )

    # Which way N, E and Z point, whenever the section is a view of the cloud
    if triad is not None:
        triad_start, triad_end, triad_tilt = triad
        _, triad_along, _, _ = _profile_axes(triad_start, triad_end)
        _draw_axis_triad(ax, triad_along, triad_tilt)

    details = ["true scale (no vertical exaggeration)"]
    if width is not None:
        details.insert(0, f"{width:g} m swath")
    if tilt_note:
        details.append(tilt_note)

    ax.set_title(f"Profile {name}–{name}′: " + ", ".join(details), fontsize=11, pad=28)
